# Generated by Django 4.2.4 on 2023-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
