# Generated by Django 4.2.4 on 2023-08-28 06:32

import RealEstate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=RealEstate.models.get_file_path, verbose_name='media/images/'),
        ),
    ]
